In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])

In [3]:
y = np.array([2,3,4,5])

In [4]:
y.reshape(x.shape)

array([[2, 3],
       [4, 5]])

In [5]:
y**2

array([ 4,  9, 16, 25])

In [6]:
2**0.5

1.4142135623730951

In [8]:
x = np.array([[1,2],[2,3]])

In [30]:
y = x.sum(axis=1)

In [31]:
y = y.reshape(1,-1)

In [33]:
y.shape

(1, 2)

In [36]:
y

array([[3, 5]])

In [38]:
z = y.repeat(5,axis=0)

In [39]:
print(z)
print(z.shape)

[[3 5]
 [3 5]
 [3 5]
 [3 5]
 [3 5]]
(5, 2)
